

steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'request and poll PAM grant'
  name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      set -e
      echo "Creating grant request..."
      NAME="$(gcloud beta pam grants create \
              --entitlement=cloud-storage-admin-jit-pam \
              --requested-duration=3600s \
              --justification="$TRIGGER_NAME : $COMMIT_SHA" \
              --location=global \
              --project="${PROJECT_ID}" \
              --format='value(name)')"

      echo "$$NAME" > /workspace/name.txt

      # initial delay
      echo "Initial delay 30s..."
      sleep 30 

      STATE=start
      while [ "$$STATE" != "ACTIVE" ]
      do
        echo "Sleeping 30s..."
        sleep 30
        STATE="$(gcloud beta pam grants search \
              --entitlement=cloud-storage-admin-jit-pam \
              --location=global \
              --project="${PROJECT_ID}" \
              --caller-relationship=had-created \
              --filter="name:$$NAME" \
              --format='value(state)')"
        echo "State: $$STATE"
      done

      # allow to take effect
      sleep 60 


- id: 'init'
  name: 'ghcr.io/opentofu/opentofu:1.8.2'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      tofu init


# [START tf-plan]
- id: 'plan'
  name: 'ghcr.io/opentofu/opentofu:1.8.2'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      tofu plan -var="project=${PROJECT_ID}"
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'ghcr.io/opentofu/opentofu:1.8.2'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      tofu apply -auto-approve -var="project=${PROJECT_ID}"

- id: 'revoke grant'
  name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      set -e
      echo "Revoking grant request..."
      # name: projects/my-project/locations/global/entitlements/ENTITLEMENT_ID/grants/GRANT_ID
      NAME="$(cat /workspace/name.txt )"

      GRANT_ID="$(echo "$${NAME}" | cut -d '/' -f 8)"
      ENTITLEMENT_ID="$(echo "$${NAME}" | cut -d '/' -f 6)"

      echo "Grant ID: $$GRANT_ID"
      echo "Entitlement: $$ENTITLEMENT_ID"

      gcloud beta pam grants revoke \
        "$$GRANT_ID" \
        --entitlement="$$ENTITLEMENT_ID" \
        --reason="apply complete" \
        --location=global \
        --project="${PROJECT_ID}"

# [END tf-apply]      
options:
  logging: CLOUD_LOGGING_ONLY